version: '3'

services:
    backend:
        image: products/node-backend:latest
        environment: 
            - environment=docker
        ports:
            - "8000:8000"
        depends_on: 
            - mongodb
    mongodb:
        image : mongo:latest
        container_name: mongodb
        ports:
        - 27017:27017
        restart: unless-stopped
    
